services:
  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
      - .docker.env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 10
  chat-service:
    build:
      context: ./chat_service
      dockerfile: ./Dockerfile
      args:
        - APP_VERSION=0.0.1
    env_file:
      - .env
      - .docker.env
    ports:
      - '8080:8080'
    depends_on:
      rabbit:
        condition: service_healthy
  mrksocket:
    build:
      context: ./mrksocket
      dockerfile: ./Dockerfile
    env_file:
      - .env
      - .docker.env
    ports:
      - '8100:8100'
    depends_on:
      rabbit:
        condition: service_healthy
  chat-app:
    build:
      context: ./chat_app
      dockerfile: ./Dockerfile
    env_file:
      - .env
      - .docker.env
    ports:
      - '3000:80'
